theme:
  active: Yellow # current playing song in list
  banner: LightYellow # the "spotify-tui" banner on launch
  error_border: Red # error dialog border
  error_text: LightRed # error message text (e.g. "Spotify API reported error 404")
  hint: Yellow # hint text in errors
  hovered: Yellow # hovered pane border
  inactive: "255, 161, 80" # borders of inactive panes
  playbar_background: Black # background of progress bar
  playbar_progress: LightYellow # filled-in part of the progress bar
  playbar_progress_text: Yellow # song length and time played/left indicator in the progress bar
  playbar_text: White # artist name in player pane
  selected: LightYellow # a) selected pane border, b) hovered item in list, & c) track title in player
  text: "255, 161, 80" # text in panes
  header: "255, 161, 80" # header text in panes (e.g. 'Title', 'Artist', etc.)

