theme:
  active: Yellow # current playing song in list
  banner: LightYellow # the "spotify-tui" banner on launch
  error_border: Red # error dialog border
  error_text: LightRed # error message text (e.g. "Spotify API reported error 404")
  hint: Yellow # hint text in errors
  hovered: LightBlue # hovered pane border
  inactive: Yellow # borders of inactive panes
  playbar_background: Black # background of progress bar
  playbar_progress: LightYellow # filled-in part of the progress bar
  playbar_progress_text: LightYellow # song length and time played/left indicator in the progress bar
  playbar_text: LightYellow # artist name in player pane
  selected: Green # a) selected pane border, b) hovered item in list, & c) track title in player
  text: LightGreen # text in panes
  header: Yellow # header text in panes (e.g. 'Title', 'Artist', etc.)

